services:
  # erp
  erp:
    container_name: erp_service
    build:
      context: .
    restart: unless-stopped
    ports:
      - 1323:1323  

  # postgres
  postgres:
    container_name: postgres_service
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # rabbitmq
  rabbitmq:
    container_name: rabbitmq_service
    image: rabbitmq:latest
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}

  # redis
  redis:
    container_name: redis_service
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  # zipkin
  zipkin:
    container_name: zipkin_service
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: dapr_network
    driver: bridge
