apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bindings-postgres
spec:
  type: bindings.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "postgres://sa:sa@localhost:5432/poc"
