apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: protocol
    value: amqp  
  - name: hostname
    value: localhost 
  - name: username
    value: broker
  - name: password
    value: broker
